### ISSUE TITLE
external solver failure

### ISSUE THREAD

**Issue by tsh2** [me-box/core-export-service#29]
Hello,
When I built the core-export-service ,using command docker build -t export-service .
The following error occured.

![confirm](https://user-images.githubusercontent.com/36950432/38717750-d5b8f674-3f23-11e8-914c-6d42566baefb.png)

Please could you tell me the solution?

**Comment by sevenEng** [comment]
Hi,
at this line: https://github.com/me-box/core-export-service/blob/master/Dockerfile#L6
you could try using `--use-internal-solver` option as
```
RUN opam pin add -y --use-internal-solver export-service /export-service
```

**Comment by tsh-box** [comment]
hello,
It is save me :) .Thank you

**Comment by Toshbrown** [comment]
@sevenEng I'm having this problem this morning ;-( 

is it worth updating the Dockerfile to always use the internal solver? I'm not sure what the drawbacks are. 

Cheers 

Tosh

**Comment by sevenEng** [comment]
hope this could help https://github.com/me-box/core-export-service/commit/a99496851a65c95763888eda103c95096362c804
